# Generated by Django 3.2.5 on 2023-11-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False, max_length=10)),
                ('daily_updates', models.BooleanField(default=False, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='coindetail',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
