# Generated by Django 4.2.7 on 2023-12-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0002_auto_20231130_1454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
