# Generated by Django 4.2.7 on 2023-12-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False, max_length=10)),
                ('daily_updates', models.BooleanField(default=False, max_length=10)),
            ],
        ),
    ]
